aiodav/__init__.py,sha256=tUhQarHj8Lu8y_W1AqsAuNVouADdK1qlMEVh3hh-pBY,99
aiodav/client.py,sha256=TCk3g2VgS8GPaPEgca7F5iT6b-2SOKobn6nfMCbNReo,45913
aiodav/exceptions.py,sha256=S-OJHgNnY85kgl2Tegu-qgmQnSUY3EhbITZzzMS_M4E,2659
aiodav/urn.py,sha256=IaiDX2n-YLbV0ZNANR_v3NHb9MDfiy2skXr9PbihkwQ,2112
aiodav/utils.py,sha256=v1iuJTLijwwDvFN1iy_1NIbiHxeAcVfcTpImJHOfJBQ,10506
aiodav-0.1.6.dist-info/LICENSE,sha256=m6FQVED-O2rDQzzTx89dp7PYYlfEd-aUGzfO7xqS9To,1084
aiodav-0.1.6.dist-info/METADATA,sha256=wFaHVQqgnsUU0SQXqUefQG6Y0umxXiaTONtSo1OAccE,2411
aiodav-0.1.6.dist-info/WHEEL,sha256=OqRkF0eY5GHssMorFjlbTIq072vpHpF60fIQA6lS9xA,92
aiodav-0.1.6.dist-info/top_level.txt,sha256=izb6vrcNoTNHhg5DB4BLgTD7d_m6lXBZo9dmeD4zjDQ,7
aiodav-0.1.6.dist-info/RECORD,,
